Ajustado a permissão do usuário EC2 para execução

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -66,31 +66,32 @@ jobs:
               sudo apt-get install -y docker.io
               sudo systemctl start docker
               sudo systemctl enable docker
-              sudo usermod -aG docker $USERNAME
             elif command -v dnf &> /dev/null
             then
               echo "Installing Docker using dnf..."
               sudo dnf install -y docker
               sudo systemctl start docker
               sudo systemctl enable docker
-              sudo usermod -aG docker $USERNAME
             else
               echo "Error: No suitable package manager found."
               exit 1
             fi
-      
-            # Verify Docker installation
-            if ! command -v docker &> /dev/null
-            then
-              echo "Docker installation failed."
-              exit 1
-            fi
-      
-            echo "Docker installed successfully."
-      
-            # Pull the latest Docker image and run the container
-            docker pull pedropucrs/agency-image:latest
-            docker stop agency-container || true
-            docker rm agency-container || true
-            docker run -d --name agency-container -p 8080:8080 pedropucrs/agency-image:latest
+          
+            sudo usermod -aG docker $USERNAME
+            newgrp docker << END
+              # Verify Docker installation
+              if ! command -v docker &> /dev/null
+              then
+                echo "Docker installation failed."
+                exit 1
+              fi
+          
+              echo "Docker installed successfully."
+          
+              # Pull the latest Docker image and run the container
+              docker pull pedropucrs/agency-image:latest
+              docker stop agency-container || true
+              docker rm agency-container || true
+              docker run -d --name agency-container -p 8080:8080 pedropucrs/agency-image:latest
+            END
           EOF
